### ISSUE TITLE
May I ask how you launch it?

### ISSUE THREAD

**Issue by Bradsr12** [melgu/TidalSwift#1]
Hello there, I have to be honest I am a stupid when it comes to these sort of things, but I hate the tidal app.. yours looked very interesting, but how do I launch it?

many thankss

**Comment by melgu** [comment]
Hi! No problem.
You download the latest version from the releases section. Then you unpack the ZIP-file, if that doesn't happen automatically. You put the app in the applications folder and then right click on it. Select open and click open in the pop-up.

The app is still work-in-progress, so expect some performance issues with very large lists. Otherwise, everything should work. Tell me, if something doesn't.

**Comment by Bradsr12** [comment]
Thank you for your instruction, but it doesn’t do anything... 
I download the zip.. 
it would unpacks.. 
I’m left with a folder that says “tidal swift-main
I drag it to applications.. 
double tap to open... 
it opens the folder... that’s all 
Then nothing.. 

Many kind regards

Richard

**Comment by melgu** [comment]
Did you go here?
https://github.com/melgu/TidalSwift/releases

And downloaded the TidalSwift.zip file for the latest release?

**Comment by Bradsr12** [comment]
Got it... 
how amazing is this! Thank you 

Many kind regards

Richard

**Comment by melgu** [comment]
You're very welcome!

**Comment by Bradsr12** [comment]
Hello there, 
Just started really using this app, and I have to saying I am really loving it!
May I ask for a feature of that is ok? I am not always on line with my Mac, so it would be useful to download an album rather than just a track, also if would be great if you could choose a folder to download too, rather than automatically choosing downloads…

I am not sure if this is at all posable ..

Many kind regards

Richard

**Comment by melgu** [comment]
Hi, sure. Nice to hear 😃 

You can already download a whole album or playlist by using the right click menu.

Choosing a download location is on the roadmap, but with a low priority for now.
